spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: chis
    password: chis
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 0  # Spring defines port automatically for multiple instances.
  #port: 8050

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}  # Each instance in Eureka server should have unique id.